version: '3.8'

services:
  planner-service:
    build:
      context: ./backend/planner-service
    ports:
      - '8080:8080'
    environment:
      - LOG_LEVEL=0
      - SERVER_PORT=8080
      - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/planner
      - RABBITMQ_CONNECTIONSTRING=amqp://user:password@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  front-end-react:
    build:
      context: ./front-end-web
    ports:
      - '3000:3000'
    depends_on:
      - planner-service

  # Flutter frontend - currently commented out
  # front-end-flutter:
  #   build:
  #     context: ./front-end-flutter
  #   depends_on:
  #     - planner-service

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
