/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "PlanPalsAWSVPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "PlanPalsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PlanPalsCognitoIdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "PlanPalsCognitoUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "PlanPalsService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "PlanPalsWeb": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "PlanPalsWebClientCognitoUserPool": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
