services:
  planner-service:
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/planner
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
