services:
  planner:
    build:
      context: .
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/code
    command: sh -c "npm i && npm run start"
