/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "PlanPalsAWSVPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "PlanPalsService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
  }
}
