name: Deploy

on:
  workflow_dispatch:
    inputs:
      atlasOwnerUsername:
        description: 'My email address'
        required: true
        type: string

jobs:
  deploy-me-daddy:
    runs-on: ubuntu-latest # EWW
    steps:
      - name: Do Stuff
        run: echo "Hello ${{ inputs.atlasOwnerUsername }}"
