name: CI

on:
  pull_request:
  push:
    branches: [main, reshaping-pp]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Wait for RabbitMQ
        run: |
          timeout 30s bash -c 'until nc -z localhost 5672; do sleep 1; done'
          sleep 10

      - name: Run PP-Server Tests
        run: |
          pushd backend/planner-service
          npm install
          npm run test -- --ci --reporters=jest-junit
          popd
      - uses: actions/upload-artifact@v4
        with:
          name: Planner Express Test Results
          path: backend/planner-service/junit.xml
      - name: Report Planner Express Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Planner Express Jest Tests
          path: backend/planner-service/junit.xml
          reporter: jest-junit
